version: '3.4'

services:
  performance_producer:
    image: ${DOCKER_REGISTRY-}performanceproducer
    build:
      context: .
      dockerfile: src/Performance_Producer/Dockerfile
    environment:
      Kafka_BootstrapServers: "boot-of1lgvp8.c3.kafka-serverless.us-west-2.amazonaws.com:9098"
      Kafka_IsPlaintext: "false"
        