apiVersion: v1
kind: Namespace
metadata:
  name: kafka-ec2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
  namespace: kafka-ec2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: ivanmds/kafka_producer:1.0.17
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: Kafka_BootstrapServers
            value: "b-3.kafkaec2poc01.jk0sfh.c12.kafka.us-west-2.amazonaws.com:9092,b-2.kafkaec2poc01.jk0sfh.c12.kafka.us-west-2.amazonaws.com:9092,b-1.kafkaec2poc01.jk0sfh.c12.kafka.us-west-2.amazonaws.com:9092"
          - name: Kafka_IsPlaintext
            value: "true"