apiVersion: v1
kind: Namespace
metadata:
  name: kafka-serverless
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: eks-gargate-pods
  namespace: kafka-serverless
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::892251137903:role/EksFargatePods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
  namespace: kafka-serverless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      serviceAccountName: eks-gargate-pods
      containers:
      - name: kafka-producer
        image: ivanmds/kafka_producer:1.0.16
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: Kafka_BootstrapServers
            value: "boot-of1lgvp8.c3.kafka-serverless.us-west-2.amazonaws.com:9098"
          - name: Kafka_IsPlaintext
            value: "false"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-service
#   namespace: kafka-serverless
# spec:
#   type: ExternalName
#   externalName: "kafka-service.default.svc.cluster.local"
#   ports:
#     - port: 9092
