
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  namespace: kafka-serverless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      serviceAccountName: eks-gargate-pods
      containers:
      - name: kafka-consumer
        image: ivanmds/kafka_consumer:1.0.4
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: Kafka_BootstrapServers
            value: "boot-of1lgvp8.c3.kafka-serverless.us-west-2.amazonaws.com:9098"
          - name: Kafka_IsPlaintext
            value: "false"
