
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  namespace: kafka-ec2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: ivanmds2/kafka_consumer:1.0.23
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        env:
          - name: Kafka_BootstrapServers
            value: "b-3.kafkaec2poc01.jk0sfh.c12.kafka.us-west-2.amazonaws.com:9092,b-2.kafkaec2poc01.jk0sfh.c12.kafka.us-west-2.amazonaws.com:9092,b-1.kafkaec2poc01.jk0sfh.c12.kafka.us-west-2.amazonaws.com:9092"
          - name: Kafka_IsPlaintext
            value: "true"
